### ISSUE TITLE
[Minor issue] Typo on the onboarding section

### ISSUE THREAD

**Issue by Kludex** [PicnicSupermarket/hiring-experience#10]
**Description**
A single typo on the onboarding section. 

**Details**
Image extracted from https://hiring.picnic.app/. Check the typo there.

![image](https://user-images.githubusercontent.com/7353520/71642517-3b129e00-2cb5-11ea-82bb-33fe51f25a22.png)

Now: `Monday: On day your first day,...`
What should be: `Monday: On your first day,...`

**Comment by Kludex** [comment]
I hope to see that Monday someday ;)

**Comment by Mordavolt** [comment]
So are we :)
