### ISSUE TITLE
[Fix Text/Link] - Github Page Link

### ISSUE THREAD

**Issue by Kludex** [PicnicSupermarket/hiring-experience#13]
At **`/src/pages/tech_stack.adoc`** the link to `Github page` is actually https://picnic.tech/ and not https://github.com/PicnicSupermarket. It may need to adapt the text, the link itself or it was intentionally done that way (:+1:).

**Check image:**
![image](https://user-images.githubusercontent.com/7353520/71872548-72ee6b00-3125-11ea-8496-1d4bd9428039.png)

**Comment by Mordavolt** [comment]
Hey @Kludex, it was intended this way since https://picnic.tech/ is the page describing our open source projects. If you click on the projects there it should open GitHub. Maybe worth rewording it to reflect what's at the end of the link. I'll look into that, thanks.
