### ISSUE TITLE
One of the videos is hidden by privacy settings

### ISSUE THREAD

**Issue by a-narsudinov** [PicnicSupermarket/hiring-experience#18]
Hello!

I've been looking through the [hiring page](https://hiring.picnic.app/) before my screening call with a recruiter and it looks like one of the videos in "Still hungry? 🍔"  section is hidden by privacy settings.

I guess [hungry.adoc](https://github.com/PicnicSupermarket/hiring-experience/blob/master/src/pages/hungry.adoc) file should be updated :)

**Comment by a-narsudinov** [comment]
The video title is `Picnic: Tech’s answer to groceries` to be more specific.

**Comment by Mordavolt** [comment]
Hello. Thanks for your suggestion, and sorry for the late reply. We just archived this project, so I'm closing this issue.
